{% set name = "xplot" %}
{% set version = "0.6.0" %}
{% set sha256 = "88e6331c6a644947ce5d80e7852cd0b016df8c4559a4b9492138074b6994868d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xplot/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py<35]
  features:   # [win]
    - vc14    # [win]

requirements:
  build:
    - toolchain
    - cmake
    - gcc-7             # [linux]
    - xeus >=0.12.0,<0.13
    - xtl >=0.4.0,<0.5
    - xproperty >=0.7.0,<0.8
    - xwidgets >=0.9.0,<0.10
    - clangdev          # [osx]
    - libcxx            # [osx]
  run:
    - xeus >=0.12.0,<0.13
    - cppzmq >=4.2.2,<4.3
    - xtl >=0.4.0,<0.5
    - xproperty >=0.7.0,<0.8
    - xwidgets >=0.9.0,<0.10

test:
  commands:
    - test -d ${PREFIX}/include/xplot  # [unix]
    - test -f ${PREFIX}/include/xplot/xmarks.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xplot/xplotConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xplot/xplotConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xplot\xmarks.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xplotConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xplotConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xplot
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ backend for the bqplot 2-D plotting library'
  doc_url: http://xplot.readthedocs.io
  dev_url: https://github.com/QuantStack/xplot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
